add nathan glaser picture and bio to website
arfc/arfc.github.io pull request #286
Opened 2023-06-16 18:35 UTC by nglaser3

## Summary of changes

Adding my picture and bio to people page of website.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Associated Issues and PRs

- Issue: #

## Associated Developers

- Dev: @

## Checklist for Reviewers

Reviewers should use [this link](/manual/guides/pull_requests.md) to get to the 
Review Checklist before they begin their review.

2023-08-22 18:01 UTC, smpark7 requested changes
This looks mostly good. You need to fix the format as I've suggested below. I'll make a separate PR to fix Ceser's formatting.

2023-09-05 19:03 UTC, nglaser3 commented on _data/people.yml
> + social:
Ok, thank you for catching that, it has been fixed

2023-09-05 19:03 UTC, nglaser3 commented on _data/people.yml
> +
Thanks for the suggestion, this has been resolved

2023-09-05 19:04 UTC, nglaser3 commented
@smpark7 Thank you for your review, please let me know if there is anything else for me to fix!

2023-09-05 19:06 UTC, smpark7 approved these changes
Looks good to me! Good job with the fixes!

2023-09-05 19:16 UTC, merged